# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  authapi:
    image: authapi
    build:
      context: .
      dockerfile: src/Services/Auth/Auth.Api/Dockerfile
    ports:
      - 7080:7080
