# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  usersgrpcservice:
    image: usersgrpcservice
    build:
      context: .
      dockerfile: src/Services/Users/Users.GrpcService/Dockerfile
    ports:
      - 5276:5276
