// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workouts.DAL;

#nullable disable

namespace Workouts.DAL.EF.Migrations
{
    [DbContext(typeof(WorkoutsDbContext))]
    partial class WorkoutsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Workouts.DAL.EF.Entities.ExerciseEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("exercise_info_id")
                        .HasColumnType("uuid");

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.Property<Guid>("workout_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("exercise_info_id");

                    b.HasIndex("workout_id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Workouts.DAL.EF.Entities.ExerciseInfoEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("muscle_group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ExerciseInfos");
                });

            modelBuilder.Entity("Workouts.DAL.EF.Entities.SetEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("exercise_id")
                        .HasColumnType("uuid");

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.Property<int>("reps")
                        .HasColumnType("integer");

                    b.Property<int>("weight")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("exercise_id");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("Workouts.DAL.EF.Entities.WorkoutEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("end_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Workouts.DAL.EF.Entities.ExerciseEntity", b =>
                {
                    b.HasOne("Workouts.DAL.EF.Entities.ExerciseInfoEntity", "exercise_info")
                        .WithMany()
                        .HasForeignKey("exercise_info_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Workouts.DAL.EF.Entities.WorkoutEntity", "workout")
                        .WithMany("exercises")
                        .HasForeignKey("workout_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("exercise_info");

                    b.Navigation("workout");
                });

            modelBuilder.Entity("Workouts.DAL.EF.Entities.SetEntity", b =>
                {
                    b.HasOne("Workouts.DAL.EF.Entities.ExerciseEntity", "exercise")
                        .WithMany("sets")
                        .HasForeignKey("exercise_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("exercise");
                });

            modelBuilder.Entity("Workouts.DAL.EF.Entities.ExerciseEntity", b =>
                {
                    b.Navigation("sets");
                });

            modelBuilder.Entity("Workouts.DAL.EF.Entities.WorkoutEntity", b =>
                {
                    b.Navigation("exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
