syntax = "proto3";

option csharp_namespace = "Users.GrpcService";

package users;

service UsersGrpc {
    rpc GetUserByEmail (GetUserRequest) returns (GetUserResponse);
    rpc CreateUser (UserMessage) returns (CreateUserResponse);
}

message GetUserRequest {
    string email = 1;
}

message GetUserResponse {
    bool success = 1;
    bool found = 2;
    UserMessage user = 3;
    string error_message = 4;
}

message UserMessage {
    string id = 1;
    string name = 2;
    string email = 3;
    string passwordHash = 4;
    string telephone = 5;
}

message CreateUserRequest {
    string name = 1;
    string email = 2;
    string passwordHash = 3;
    string telephone = 4;
}  

message CreateUserResponse { 
    bool success = 1;
    string id = 2;
    string error_message = 3;
}