syntax = "proto3";

option csharp_namespace = "Users.GrpcService";

package users;

service UsersGrpc {
    rpc GetUserByEmail (GetUserRequest) returns (GetUserResponse);
    rpc CreateUser (UserMessage) returns (CreateUserResponse);
}

message GetUserRequest {
    string email = 1;
}

message GetUserResponse {
    bool found = 1;
    UserMessage user = 2;
}

message UserMessage {
    string name = 2;
    string email = 3;
    string passwordHash = 4;
    string telephone = 5;
}

message CreateUserResponse { 
    bool success = 1;
    string error_message = 2;
}